ruby/nepal-portal/config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#home'
   get 'emergency_contacts' => 'static_pages#emergency'
   get 'about' => 'static_pages#about'
   get 'loadshedding' => 'static_pages#loadshedding'
   resources :petrol_finder, only: [ :index ]

end

ruby/nepal-portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/nepal-portal/app/controllers/petrol_finder_controller.rb
class PetrolFinderController < ApplicationController
  def index
  end
end

ruby/nepal-portal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def emergency
  end
  def loadshedding
  end
  def about
  end
end

ruby/nepal-portal/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/nepal-portal/app/helpers/petrol_finder_helper.rb
module PetrolFinderHelper
end

ruby/nepal-portal/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

ruby/nepal-portal/app/views/layouts/_footer.html.slim
footer.footer
  small
    'Developed by <a href="https://www.facebook.com/lawrence.khadka.7">  Lawrence Khadka
  small.pull-right
    nav
      ul
        li = link_to 'About', about_path
        li
          a href = "https://lawatlife.wordpress.com/" Blog
        li
          a href="https://ekantipur.com" News

ruby/nepal-portal/app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  div.container-fluid
    div.navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#myNavbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand = link_to 'NEPAL PORTAL', '/', id: 'logo'
    div.collapse.navbar-collapse#myNavbar bs-active-link=""
      ul.nav.navbar-nav.navbar-left
        li <a href="/"><i class="fa fa-home fa-inverse"></i> Home</a>
        li <a href="/petrol_finder"><i class="fa fa-tint fa-inverse"></i> Petrol Finder</a>
        li <a href="/loadshedding"><i class="fa fa-lightbulb-o fa-inverse"></i> Loadshedding Schedule</a>
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"  Misc <i class="fa fa-level-down fa-inverse"></i>
          ul.dropdown-menu role="menu"
            li = link_to 'Emergency Numbers', emergency_contacts_path
        li <a href="/about"><i class="fa fa-info fa-inverse"></i> About</a>

ruby/nepal-portal/app/views/layouts/_shim.html.slim
'<!--[if	lt	IE	9]>
  <script	src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
'<![endif]-->

ruby/nepal-portal/app/views/layouts/_social.html.slim
div.social-links
  p#social-link <a id="social" href="https://github.com/LKhadka/Nepal-Portal"><i class="fa fa-github fa-5x" title="Fork me on GitHub!"></i></a>
  p#social-link <a id="social" href="https://facebook.com/sharer.php?u=https://nepalportal.herokuapp.com"><i class="fa fa-facebook fa-5x" title="Share me on Facebook!"></i></a>
  p#social-link <a id="social" href="https://twitter.com/share" class="twitter-share-button" data-url="http://nepalportal.herokuapp.com" data-text="Check out this site!!" title="Retweet me on Twitter!"><i class="fa fa-twitter fa-5x"></i></a>

ruby/nepal-portal/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title)
      ' Nepal Portal
    = csrf_meta_tags
    = javascript_include_tag 'application', :defer => "defer"
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'favicon.ico'
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.6.0/flexslider.min.css"
    script defer="" src="https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.6.0/jquery.flexslider.min.js" type="text/javascript"


    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    = render 'layouts/shim'
  body.container
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'
  //Google Analytics Tracking Code
  '<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-71888357-2', 'auto');
      ga('send', 'pageview');

    </script>

ruby/nepal-portal/app/views/petrol_finder/index.html.slim
-provide(:title, 'Petrol Finder | ')
article ng-app="nepal"
  div.row
    div.col-md-3.col-xs-0.col-sm-0
      div.row
        div.col-md-2.col-xs-1
        div.col-md-7.col-xs-10.hidden-xs.hidden-sm style="padding-top: 65px;"
          h3.h4.hidden-xs.hidden-sm Distribution date
          select.form-control.hidden-xs.hidden-sm name="date" ng-model="petrol.date" ng-init="petrol.date = '2016/01/25'"
            option ng-option="" ng-selected="selected" value="2016/01/25" Jan 25, 2016
            option ng-option="" value="2016/01/22" Jan 22, 2016
            option ng-option="" value="2016/01/20" Jan 20, 2016
            option ng-option="" value="2016/01/06" Jan 06, 2016
        div.col-md-3.col-xs-1
    div.col-md-8.col-xs-12
      h1.h2 <i class="fa fa-tint"></i> Petrol Finder
      div#map_20160125 style = "height: 600px;" ng-if="petrol.date == '2016/01/25'"
        petrol-finder
      div#map_20160122 style = "height: 600px;" ng-if="petrol.date == '2016/01/22'"
        petrol-finder
      div#map_20160120 style = "height: 600px;" ng-if="petrol.date == '2016/01/20'"
        petrol-finder
      div#map_20160106 style = "height: 600px;" ng-if="petrol.date == '2016/01/06'"
        petrol-finder
      small
        em.pull-right Click on the circle for more info! <br/>
        span ng-if="petrol.date == '2016/01/25'" For motorcycles/scooters belonging to <strong style="color: rgb(0,128,128)">lot no. 51 and up</strong>
        span ng-if="petrol.date == '2016/01/22'" For motorcycles/scooters between <strong style="color: rgb(0,128,128)">lot no. 31 and 50</strong>
        span ng-if="petrol.date == '2016/01/20'" For motorcycles/scooters between <strong style="color: rgb(0,128,128)">lot no. 1 and 30</strong>
        span ng-if="petrol.date == '2016/01/06'" For four wheelers between <strong style="color: rgb(0,128,128)">lot no. 1 and 6</strong>
    div.col-md-1.col-xs-0.col-sm-0
  div.row.visible-sm.visible-xs
    div.col-xs-2
    div.col-xs-8 style="padding-top: 30px;"
      h3.h4 Distribution date
      select.form-control name="date" ng-model="petrol.date" ng-init="petrol.date = '2016/01/25'"
        option ng-option="" ng-selected="selected" value="2016/01/25" Jan 25, 2016
        option ng-option="" value="2016/01/22" Jan 22, 2016
        option ng-option="" value="2016/01/20" Jan 20, 2016
        option ng-option="" value="2016/01/06" Jan 06, 2016
    div.col-xs-2
  br
  hr
  br
  div.row
    div.col-md-1
    div.col-md-10
      h2.h1.text-justify
        'What is Petrol Finder?
    div.col-md-1
  div.row
    div.col-md-1
    div.col-md-10
      div.text-justify
        'Petrol Finder uses the map provided by <a href=”http://openstreetmap.org/”> Open Srreet Map </a> for displaying the petrol pumps where the fuel is going to be distributed for the certain lots of vehicles for specific dates. The list of petrol pumps is provided by Nepal Oil Corporation and can be viewed <a href='http://nepaloil.com.np/news-events/Notice/5/'> here.</a>
    div.col-md-1
  p
  div.row
    div.col-md-1
    div.col-md-10
      h2.text-justify
        'Why?
    div.col-md-1
  div.row
    div.col-md-1
    div.col-md-10
      div.text-justify
        'Currently, Nepal is facing a huge humanitarian crisis due to economic blockade at the southern custom points. There is a complete shortage of fuel.  The fuel crisis has made the lives of the people of Nepal very hard.  People from Kathmandu are forced to buy wood to cook food due to the lack of the cooking gas/Liquified Petroleum Gas (LPG) cylinders.
    div.col-md-1
  p
  div.row
    div.col-md-2.col-xs-1
    div.col-md-8.col-xs-10
      div.hidden-xs.hidden-sm
        div#pieChart cost-pie-chart-one=""
      div.visible-xs.visible-sm
        div.text-center
          h3.h4 Average Monthly Spending of Every Household of Five to Cook Food in 2003
        div#pie1
          div#tooltip2 class="hidden"
            p <strong>Expenditure: NRS <span style="color: rgb(0,128,128)" id = "value"> x</span></strong>
        div.pull-right
          em
            small Source: Amrit M Nakarmi, Professor, Tribhuvan University <br/>
    div.col-md-2.col-xs-1
  p
  div.row
    div.col-md-2.col-xs-1
    div.col-md-8.col-xs-10
      div.hidden-xs.hidden-sm
        div#pieChart cost-pie-chart-two=""
      div.visible-xs.visible-sm
        div.text-center
          h3.h4 Average Monthly Spending of Every Household of Five to Cook Food in 2015
        div#pie2
          div#tooltip2 class="hidden"
            p <strong>Expenditure: NRS <span style="color: rgb(0,128,128)" id = "value"> x</span></strong>
        div.pull-right
          em
            small Source: Amrit M Nakarmi, Professor, Tribhuvan University <br/>
    div.col-md-2.col-xs-1
  p
  div.row
    div.col-md-1
    div.col-md-10
      div.pull-left
        'The economic blockade has increased expenses for the people. The costs of making food have also increased thanks to the skyrocketing inflation and the economic blockade which is evident from the pie chart comparing the cost of making food between 2003 and 2015 .This blockade comes at the time when Nepal is just recovering from the disastrous earthquakes that struck Nepal on April and June.
    div.col-md-1
  p
  div.row
    div.col-md-1
    div.col-md-10
      small
        em The Geojson data for the petrol pumps can be downloaded from Nepal Portal's<a href="https://github.com/LKhadka/Nepal-Portal/tree/master/public"> GitHub</a> page. <br/>
        em The notice about the petrol pumps from NOC can be found<a href="http://nepaloil.com.np/news/details.php?n=84"> here.</a>
  div.col-md-1

ruby/nepal-portal/app/views/static_pages/about.html.slim
- provide(:title, 'About | ')
article ng-app ="nepal"
  div#bubble bubble=""
div.row
  div.col-md-3.col-xs-1
  div.col-md-6.col-xs-10
    h1.h2.text-center About
    h3.h4.text-justify
     p This site was developed by Lawrence Khadka. He can be reached <a href="https://www.facebook.com/lawrence.khadka.7"> here.</a></p><p>You can read all about the developer's experience on making this page <a href="https://lawatlife.wordpress.com/">here</a>
  div.col-md-3.col-xs-1
    = render 'layouts/social'
div#vis

ruby/nepal-portal/app/views/static_pages/emergency.html.slim
- provide(:title, 'Emergency Contacts | ')
div.row
  div.col-md-3.col-xs-0
  div.col-md-6.col-xs-12
    h1.h2 Emergency Numbers
    hr
    table.table.table-striped
      thead
        tr
          th Name
          th Phone Number
      tbody
        tr
          td Police Control Room
          td 100
        tr
          td Traffic Police Control Room
          td 103
        tr
          td Fire Fighters
          td 101
        tr
          td Emergency Police Service
          td 4228435
        tr
          td Crime Informtion
          td 4412748
        tr
          td Child Missing
          td 104
        tr
          td Nepal Electricity Authority
          td 4153052
        tr
          td Blood Bank, Pradarshani Marg
          td 4225344
        tr
          td Nepal Red Cross Society, Teku
          td 4270650
        tr
          td Bhaktapur Red Cross
          td 6612266
        tr
          td Army Hospital
          td 4271940
        tr
          td Bir Hospital
          td 4223807
        tr
          td Bhaktapur Cancer Hospital
          td 6611532
        tr
          td Chirayu National Hospital
          td 4382382
        tr
          td Kanti Children Hospital
          td 4411134
        tr
          td Norvic Hospital
          td 4258554
        tr
          td Police Hospital
          td 4412430
        tr
          td Star Hospital, Sanepa
          td 5550197
        tr
          td Teaching Hospital
          td 4412404
        tr
          td Grande Hospital
          td 5159266
        tr
          td Tilganga Hospital
          td 4423684
        tr
          td Hearse (Shav Vahan)
          td 6612266
  div.col-md-3.col-xs-0

ruby/nepal-portal/app/views/static_pages/home.html.slim
- provide(:title, 'Home | ')
div.row
  div.col-md-1.col-xs-0
  div.col-md-10.col-xs-10
    div.center
      h1.h1.text-uppercase.text-center Welcome to Nepal Portal!
      p.text-justify Nepal Portal was developed with the main intention of helping the people by making it easier to find the petrol pumps where the fuel is being distributed in this hard time.
      div.flexslider#homepage-images style="{height: 400px;}"
        ul.slides
          li
            = link_to image_tag('petrol3.jpg', alt: "Back to the Past", title: "Back to the Past", class: "responsive-img center-block"), '#'
            p.flex-caption People buying logs for cooking.
          li
            = link_to image_tag('petrol4.jpg', alt: "The Daily of an Average Nepalese", title: "The Daily of an Average Nepalese", class: "responsive-img center-block"), '#'
            p.flex-caption People rushing to ride the bus.
          li
            = link_to image_tag('petrol5.jpg', alt: "Black Marketing", title: "Black Marketing", class: "responsive-img center-block"), '#'
            p.flex-caption A cartoon depicting the current black marketing of fuel in Nepal.
          li
            = link_to image_tag('petrol6.jpg', alt: "A Dangerous Ride", title: "A Dangerous Ride", class: "responsive-img center-block"), '#'
            p.flex-caption A child being carried to the hood of the bus due to the lack of seats.
          li
            = link_to image_tag('petrol7.jpg', alt: "A Difficult Time", title: "A Difficult Time", class: "responsive-img center-block"), '#'
            p.flex-caption A child cooking food from an almost empty cylinder which is supposed to be replaced soon.
          li
            = link_to image_tag('petrol8.jpg', alt: "Left Hanging", title: "Left Hanging", class: "responsive-img center-block"), '#'
            p.flex-caption People hanging on a moving bus.
          li
            = link_to image_tag('petrol9.jpg', alt: "A Reflection", title: "A Reflection", class: "responsive-img center-block"), '#'
            p.flex-caption Art depicting the current situation of the Nepalese people.
          li
            = link_to image_tag('petrol10.jpg', alt: "A Daily Task", title: "A Daily Task", class: "responsive-img center-block"), '#'
            p.flex-caption Women struggling to get on the bus. The people are forced to travel in such dangerous ways.
  div.col-md-1
    = render 'layouts/social'


h3.h4 Made With <i class="fa fa-heart"></i> in Kathmandu Using
div.row
  div.col-xs-1
  div.col-md-12.col-xs-10
    = link_to image_tag('rails.png',      alt: 'Ruby on Rails', title:'Ruby on Rails', id: 'image1'), 'http://rubyonrails.org/'
    = link_to image_tag('angularjs.png',  alt: 'AngularJS',     title:'AngularJS',     id: 'image1'), 'http://angularjs.org/'
    = link_to image_tag('d3.png',         alt: 'D3.js',         title:'D3.js',         id: 'image1'), 'http://d3js.org/'
    = link_to image_tag('bootstrap.png',  alt: 'Bootstrap',     title:'Bootstrap',     id: 'image1'), 'http://getbootstrap.com/'
    = link_to image_tag('html5.png',      alt: 'HTML5',         title:'HTML5',         id: 'image1'), 'http://postgresql.org/'
    = link_to image_tag('leaflet.svg',    alt: 'Leaflet',       title:'Leaflet',       id: 'image1'), 'http://leafletjs.com/'
  div.col-xs-1

ruby/nepal-portal/app/views/static_pages/loadshedding.html.slim
- provide(:title, 'Loadshedding Schedule | ')
div.row
  div.col-md-2.col-xs-0
  div.col-md-8.col-xs-12
    h2 Loadshedding Schedule
    hr
    ul.nav.nav-tabs data-tabs="tabs"
      li.active
        a data-toggle="tab" href="#group1"  Group 1
      li
        a data-toggle="tab" href="#group2"  Group 2
      li
        a data-toggle="tab" href="#group3"  Group 3
      li
        a data-toggle="tab" href="#group4"  Group 4
      li
        a data-toggle="tab" href="#group5"  Group 5
      li
        a data-toggle="tab" href="#group6"  Group 6
      li
        a data-toggle="tab" href="#group7"  Group 7
    .tab-content
      #group1.tab-pane.active
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours

            tr
              td MON
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td TUE
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td WED
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td THU
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td FRI
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td SAT
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
      #group2.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td MON
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
            tr
              td TUE
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td WED
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td THU
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td FRI
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td SAT
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
      #group3.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td MON
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td TUE
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
            tr
              td WED
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td THU
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td FRI
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td SAT
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
      #group4.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td MON
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td TUE
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td WED
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
            tr
              td THU
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td FRI
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td SAT
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
      #group5.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td MON
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td TUE
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td WED
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td THU
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
            tr
              td FRI
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td SAT
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
      #group6.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td MON
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td TUE
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td WED
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td THU
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td FRI
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
            tr
              td SAT
              td 11:00 am - 07:00 pm
              td 8 hours
      #group7.tab-pane
        table.table
          thead
            tr
              th DAY
              th TIME
              th HOURS
          tbody
            tr
              td SUN
              td 11:00 am - 07:00 pm
              td 8 hours
            tr
              td MON
              td 03:00 am - 10:00 pm
              td 7 hours
            tr
              td
              td 02:00 pm - 08:00 pm
              td 6 hours
            tr
              td TUE
              td 06:00 am - 03:00 pm
              td 9 hours
            tr
              td
              td 07:00 pm - 11:00 pm
              td 4 hours
            tr
              td WED
              td 10:00 am - 04:00 pm
              td 6 hours
            tr
              td
              td 08:00 pm - 12:00 pm
              td 4 hours
            tr
              td THU
              td 04:00 am - 12:00 pm
              td 8 hours
            tr
              td
              td 04:00 pm - 10:00 pm
              td 6 hours
            tr
              td FRI
              td 04:30 am - 11:00 am
              td 6 hours 30 min
            tr
              td
              td 03:00 pm – 09:00 pm
              td 6 hours
            tr
              td SAT
              td 05:00 am - 02:00 pm
              td 9 hours
            tr
              td
              td 06:00 pm - 10:00 pm
              td 4 hours
      hr
      em Current Schedule has been effective since 2072-9-20 BS (2016-01-04 AD)
  div.col-md-2.col-xs-0
br
br
div.row
  div.col-md-1
  div.col-md-10
    h2.h1.text-justify
      'A Look at Load Shedding
  div.col-md-1
div.row
  div.col-md-1
  div.col-md-10
    div.text-justify
      'The Nepalese people are currently facing eleven to twelve hours of load shedding each day which is most likely to go up in the coming days. Nepal generates 762 MW of hydroelectricity. But during winter, power generation capacity dips by more than half because most of the hydro projects in operation are run-of-the-river.
  div.col-md-1
p
div.row
  div.col-md-1
  div.col-md-10
    div.text-justify
      'Run-of-the-river hydro projects generate electricity whenever there is water in the river. So, as soon as water level dips, electricity production from these projects falls. This problem is become even worse during this winter because several hydro plants that were damaged during earthquakes of April and May have reduced power generation by 80 MW.
  div.col-md-1
br
div.row
  div.col-md-1
  div.col-md-10
    div.text-center
      h3.h4 Power Generation and Consumption for Summers and Winters of 2015 and 2018* Respectively
    div#viz
      div#tooltip1 class='hidden'
        p <strong>Power:<span id = "value" style="color: rgb(0,128,128)"> 100 </span> MW</strong>
    div.pull-right
      em Source: Nepal Electricity Authority (NEA) <br/>
      small <em> *Expected </em>
  div.col-md-1
p
div.row
  div.col-md-1
  div.col-md-10
    div.text-justify
      'Nepal Electricity Authority (NEA), the state-owned power utility company, expects to generate only 327 MW of electricity this winter whereas the peak electricity demand currently stands at around 1,500 MW. NEA expects to add 821 MW to the national grid within two to three years but they are all from run-of-the-river plants whose production would fall to 215 MW during winter.Nepal has been seeing a growth of 7.56 percent growth in peak hour electricity consumption in 2015.
  div.col-md-1
p
div.row
  div.col-md-1
  div.col-md-10
    div.text-justify
      'Currently, a hydro project developer has to make rounds of seven ministries and 23 government departments and deal with 36 different laws prior to beginning construction of hydro projects.  Nepal could reduce its petroleum bills by Rs 50 billion (approx. &dollar; 470 milliion) if it can add 1,300 MW of electricity. The investment needed to generate this quantity of electricity is Rs 210 billion (approx. &dollar; 4.4 billion) but it would save the nation Rs 1 trillion (approx. &dollar; 9.4 billion) over the next twenty years and cut the reliance on fossil fuels.
  div.col-md-1